// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppEnt
{
    public partial class Aluno
    {

        [Key]
        [Column("idAluno")]
        public long IdAluno { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(200)]
        public string Nome { get; set; }
        [Required]
        [Column("telefone")]
        [StringLength(20)]
        public string Telefone { get; set; }
    }
}